### ISSUE TITLE
I can't install @express/openapi package

### ISSUE THREAD

**Issue by cartoon1110** [wesleytodd/express-openapi#1]
I ran the command 'npm install --save @express/openapi' to install this package.
but, npm returned  404 Not Found response.
(@express/openapi is not in the npm registry)

So, How can i install this package?

**Comment by wesleytodd** [comment]
Hey @cartoon1110, sorry about the difficulty.  We were having discussions about how to move forward with the npm scope.  In the mean time I have published this under my personal scope `@wesleytodd/openapi`.  I will maintain that until we get the `@expressjs` scope figured out.

I added a note to the readme for this, hope that helps.

**Comment by AustinGil** [comment]
@wesleytodd Is there any news on this? Is this still planned to integrate with Express? Or is the project halted?

**Comment by nabati** [comment]
+1 on @AustinGil s question

**Comment by AustinGil** [comment]
I got a response on Twitter regarding the maintenance of this project. Seems like it's still maintained, although it may not join the Express namespace soon:

https://twitter.com/wesleytodd/status/1336784193116835843
