### ISSUE TITLE
Obtaining openapi.yaml instead of openapi.json

### ISSUE THREAD

**Issue by MeCode4Food** [wesleytodd/express-openapi#13]
Hi, often when I am trying to share the openapi specs, I have to go to localhost:8080/openapi.json, grab the json, convert it to  a YAML format, and then share it.

It seems like a lot of places that use OpenAPI tend to accept it in YAML format instead of json. 

Do you think by any chance that there is a way to do so from within the express server itself?

**Comment by wesleytodd** [comment]
I think this would be a great addition.  A PR for this would be awesome.  I think just as you say, if the request was for `.yml` or `.yaml` then run it through [a json to yaml step](https://eemeli.org/yaml/#yaml-stringify) before responding.

**Comment by MeCode4Food** [comment]
Added a PR to support this feature

https://github.com/wesleytodd/express-openapi/pull/15

**Comment by MeCode4Food** [comment]
Originally wanted to run multiple requests inside the "create a basic valid OpenAPI document and serve test on an express app" test, but I don't know if `supertest` supports that (tried with promises using async await, didn't really work). Hence the duplication of tests for different formats

**Comment by wesleytodd** [comment]
I am going to close this since there is a PR open.  Still need that to be updated, but updates can happen over there from now on.
