### ISSUE TITLE
Get generated OpenAPI document

### ISSUE THREAD

**Issue by lembdev** [wesleytodd/express-openapi#16]
I need to get the generated document schema.

I'm trying to get it from `oapi.document`, but it doesn't contain `path` information.

```javascript
const openapi = require('@wesleytodd/openapi')
const app = require('express')()

const oapi = openapi({
  openapi: '3.0.0',
  info: {
    title: 'Express Application',
    description: 'Generated docs from an Express api',
    version: '1.0.0',
  }
})

app.use(oapi)

app.get('/', oapi.path({
  responses: {
    200: {
      description: 'Successful response',
      content: {
        'application/json': {
          schema: {
            type: 'object',
            properties: {
              hello: { type: 'string' }
            }
          }
        }
      }
    }
  }
}), (req, res) => {
  res.json({
    hello: 'world'
  })
})

console.log(oapi.document)
```

result:
```javascript
{
  openapi: '3.0.0',
  info: {
    title: 'Express Application',
    version: '1.0.0',
    description: 'Generated docs from an Express api'
  },
  paths: {}
}
```

Any solutions?

**Comment by MeCode4Food** [comment]
That's because it only builds the openapi specs on a request trigger. It doesn't build it on startup. I'm not sure if this is the intended mechanism, although I think it could be nice to have.

**Comment by wesleytodd** [comment]
That is the intended mechinism, mostly because folks do some wild stuff with their route definitions, and you really cannot be sure when you are safe to iterate the router stack.  That said, you can always call `.generateDocument` and it will generate one from the current state of the router.  If you have registered all of your `.path` middleware this should work correctly for you.

**Comment by wesleytodd** [comment]
Going to close this because I think the question was answered.  Feel free to comment if you think it needs more clarification.
