### ISSUE TITLE
Is this production ready?

### ISSUE THREAD

**Issue by JotaPe** [wesleytodd/express-openapi#24]
I would like to know if this is usable on production, at my company we don't care too much about 100% stability, but some stability is kinda good, Is this stable enough to be used on production environment?

**Comment by r3na** [comment]
We've been using it for some time now and feel it's ready for production.

**Comment by wesleytodd** [comment]
Yeah I think it is. It for sure withstood the usage we put it to on a few teams at work.  Happy to help answer questions you might have if there are things you are concerned about with it.

**Comment by wesleytodd** [comment]
Going to close this. Folks seem to be happy with it and using it "in production".
