### ISSUE TITLE
bug with parameters; always string

### ISSUE THREAD

**Issue by r3na** [wesleytodd/express-openapi#26]
The type should be provided by the app as well and not hard coded as "string".
https://github.com/wesleytodd/express-openapi/blob/a38331330f005a91527bea28cb78521c5293cf8b/lib/generate-doc.js#L42

Parameters can be "integer" for example.
https://swagger.io/docs/specification/describing-parameters/

**Comment by wesleytodd** [comment]
Closing in favor of the pr.
