### ISSUE TITLE
npm update/install  fails because of redoc old version

### ISSUE THREAD

**Issue by davellx** [wesleytodd/express-openapi#38]
Hello,

I tried to do a `npm update` yesterday but it failed : the command is stuck in the idealTree part. (it's the same with an `npm install` if I don't have any package-lock.json)
It seems this package is the culprit... to be specific I tried to check the dependancies and installing redoc on my own dependancies seems to resolve the problem. 
Maybe updating the dependancies in this package would solve my problem.

So my questions are : 
1/ Am I the only one with this problem ?
2/ Would it be possible to update de the dependancies for the npm package ? It would also solve moderate severity vulnerabilities reported by npm.
3/ I know that swagger & redoc are very useful but wouldn't it be more convenient to let user decide if they want to install one or the other and not forcing to install them along the lib ? 

Thanks in advance,

**Comment by wesleytodd** [comment]
Hey @davellx! Can you post a few more details about your setup? Specifically the npm version you are using?

> Am I the only one with this problem ?

I seem to be able to replicate, so no not just you. What I am seeing is it just hang at the line `idealTree:express-oapi: timing idealTree:#root Completed in 1599ms`, is that exactly what you are seeing? Or do you see something different?

> Would it be possible to update de the dependancies for the npm package ?

Yeah I can do that today.

>  know that swagger & redoc are very useful but wouldn't it be more convenient to let user decide if they want to install one or the other and not forcing to install them along the lib ?

I guess I could be persuaded to have those as optional dependencies. I could see trying to require them and failing gracefully if they are not present. Open to seeing a PR implementing this.

**Comment by wesleytodd** [comment]
Yeah I am going to say this looks like an npm bug. The whole process completely hangs after `npm http fetch GET 200 https://registry.npmjs.org/@redocly%2fajv 616ms (cache revalidated)`. I will work on getting this package updated, but also I think I will try and see if I can replicate this on newest npm versions.

**Comment by wesleytodd** [comment]
Yeah this is going to be a breaking change to get these updated. I *think* that is a good thing, but just wanted you to be prepared.

**Comment by wesleytodd** [comment]
Ok, everything is updated in `0.2.0`. Let me know if that fixes your issues.

**Comment by davellx** [comment]
Hello,

Thanks a lot for answering so quickly.
Unfortunately it still doesn't work for me.

On my last failed install it hanged at :
`npm http fetch GET 200 https://registry.npmjs.org/oas-resolver 823ms (cache miss)`

I still think that the old version of redoc is the main problem for me, but I don't want to install redoc on my main package.json since I don't have any use for this.

PS : the fork @unleash/express-openapi, that removed redoc works with no problem, I'll stick with that for the moment, thanks again for your time.

**Comment by wesleytodd** [comment]
Hm interesting. Not sure why then it worked for me. If you could post the npm and node version you are using that would be awesome. I can probably put together the PR I mentioned to make the UI tools optional, but I wanted to give you the opportunity first since you reported it.

**Comment by davellx** [comment]
Here are the npm/node version on my machine : 
```
npm: '9.8.1',
node: '18.17.1',
```

**Comment by wesleytodd** [comment]
Yeah I was able to replicated with those versions but only when installing `@wesleytodd/openapi` into a new project, not actually installing `redoc` in this repo. So Here is that PR to make it optional: https://github.com/wesleytodd/express-openapi/pull/41
