### ISSUE TITLE
Webpack fail 

### ISSUE THREAD

**Issue by anson2004** [wesleytodd/express-openapi#5]
Hello,

   I am trying to use webpack to pack my web application.
   And I get following error messages here. It seems function serveRedoc  does not work well with webpack. I attached my example project.

In the attached project,  I run:
```
npm install
npx webpack
node build/index-bundle.js
```

 
```

internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number
    at validateString (internal/validators.js:125:11)
    at Object.resolve (path.js:161:7)
    at Object.e.exports.serveRedoc (C:\Users\liangyi\Desktop\nodeProject\oapi\build\index-bundle.js:1:4883)
    at e.exports (C:\Users\liangyi\Desktop\nodeProject\oapi\build\index-bundle.js:1:3048)
    at Object.<anonymous> (C:\Users\liangyi\Desktop\nodeProject\oapi\build\index-bundle.js:1:1206)
    at t (C:\Users\liangyi\Desktop\nodeProject\oapi\build\index-bundle.js:1:110)
    at C:\Users\liangyi\Desktop\nodeProject\oapi\build\index-bundle.js:1:902
    at Object.<anonymous> (C:\Users\liangyi\Desktop\nodeProject\oapi\build\index-bundle.js:1:911)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

Here is my webpack.config.js

```
const path = require('path');
const fs = require('fs');

const nodeModules = {};
fs.readdirSync('node_modules')
    .filter(function (x) {
        return ['.bin'].indexOf(x) === -1;
    })
    .forEach(function (mod) {
        nodeModules[mod] = 'commonjs ' + mod;
    });


module.exports = {
    entry: './index.js',
    target: 'node',
    output: {
        path: path.join(__dirname, 'build'),
        filename: 'index-bundle.js'
    },
    externals: nodeModules
};
```

Could you help me with this case?

[oapi.zip](https://github.com/wesleytodd/express-openapi/files/4133982/oapi.zip)

Best regard,
Yiqing Liang

**Comment by wesleytodd** [comment]
Hi @anson2004, this package uses nodes `require.resolve` api, so I think webpack would not pick it up.  I am not going to download a zip file (I do value my computer's security), but if you want to post a link to a github repo I could take a quick look and see if there was something simple to do to fix this issue.

**Comment by anson2004** [comment]
Hi @wesleytodd , thanks for the reply. Here is the github link I just created for the sample code https://github.com/anson2004/openapi-test. Let me know if you need any further information.

Br, Yiqing

**Comment by wesleytodd** [comment]
Ok, so webpack in your example repo is converting this:

https://github.com/wesleytodd/express-openapi/blob/master/lib/ui.js#L6
```javascript
path.resolve(require.resolve('redoc'), '..')
```

To:

```javascript
o(r.resolve(11,".."))
```

So the string `"redoc"` is converted to `11`. Obviously node doesn't like that number when it expects a string.  I would report this as a bug to webpack, as there is nothing we can do here to resolve this issue.

**Comment by wesleytodd** [comment]
Closing this for now.  If you feel like it is something we can fix here go ahead and reopen it.
