### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by wesleytodd** [wesleytodd/express-openapi#53]
Just wanted to put together a quick 1.0.0 plan. We have two breaking changes lined up:

- #52
- #50

I was thinking maybe we should quickly tackle a few of the open issues as well before we release?

- #20: This one might require some work adding a test that covers it. (@AustinGil not sure if you are still using the package and/or want to help)
- #25: This should be relatively easy. If we wanted we could even generate the .d.ts files and test them (ex https://github.com/pkgjs/nv/pull/15). 
- #22: Also TS related, not sure I remember enough about this one to be sure what we need to do or if it is a reasonable ask.
- #19: This one maybe @AustinGil could comment on as well? Do we want this?

Maybe we don't need to land all this, most of these are non breaking and could go out after 1.0.0, but just wanted to see what folks thought.

cc @Megapixel99 @enov @thomasheartman

**Comment by Megapixel99** [comment]
I just created the branch `release/v1.0.0` and retargeted both PRs.

**Comment by Megapixel99** [comment]
Both #50 and #52 are merged. I will look at the other issues now.
