### ISSUE TITLE
Using with router in node submodules doesn't show up in json

### ISSUE THREAD

**Issue by kinabalu** [wesleytodd/express-openapi#9]
I've got a test project here which is small: https://github.com/kinabalu/express-openapi-router-test

I've got a setup where the directory structure is

`./routes/<module>/index.js` and we use a router for all the endpoints in that `/module` like shown in the example. Only problem is, when using `oapi.path` it seems to call things in the express-openapi codebase, but things get added later and never get added to the `openapi.json`. Not sure if I have some order done incorrectly?

**Comment by wesleytodd** [comment]
This is related to this: https://github.com/wesleytodd/express-openapi/pull/8

Basically, nested routers need to be added.  That PR might be the right approach, but there were way to many unrelated changes in it to justify me spending time to review it.  If you want to clean it up and apply *only* the changes to get this feature landed I would be able to push a release pretty quickly.  This is the only feature I was waiting on to re-bring up the conversation of moving this into the Express org.

**Comment by kinabalu** [comment]
@wesleytodd I pulled only the relevant bits out, integrated the test that was added from #8 and have a PR open for you to review. I've also pulled this into my test project referenced above, and a cursory test seems to validate that it works. Let me know if you need anything else!

**Comment by wesleytodd** [comment]
Published in `0.1.0`.
